<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Karir</name>
   <tag></tag>
   <elementGuidId>d396da8c-ef86-47fb-aaba-c64d56f165c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/header/div[2]/div/nav/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>463ab0b7-08d9-43be-b9ac-42871515f472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white </value>
      <webElementGuid>5c0a9bee-ed49-4b2a-b2e1-ada6a393760b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>00eb392d-2aed-4aed-8555-f31085e639c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/karir/</value>
      <webElementGuid>cf69128d-4dc8-465b-97f2-89815affe289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Karir</value>
      <webElementGuid>00ee5cbe-d74f-415e-bd56-24c0746803ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative w-screen antialiased __variable_241a51 __variable_43c742 font-sans&quot;]/div[@class=&quot;absolute top-0 z-10&quot;]/header[@class=&quot;sticky top-0 z-50 w-screen bg-transparent fadeInDown transition-all duration-1000&quot;]/div[@class=&quot;side-padding relative z-50 flex max-h-[120px] items-center justify-between py-10 text-white mobile:pb-4 tablet:pb-8&quot;]/div[1]/nav[@class=&quot;mx-4 flex&quot;]/ul[@class=&quot;flex flex-wrap items-center gap-[32px] gap-y-10 text-14 font-medium leading-6 laptop:text-16 desktop:gap-[72px]&quot;]/li[@class=&quot;group/menu relative border-white py-2 hover:border-b&quot;]/a[@class=&quot;text-white&quot;]</value>
      <webElementGuid>fbb25a8c-b0af-44bb-a1da-ce6ce7283af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/header/div[2]/div/nav/ul/li[5]/a</value>
      <webElementGuid>fd8e0250-380a-4747-91bf-1ab38211f682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Karir')]</value>
      <webElementGuid>26360e7c-d596-4907-8206-4c4a3c81ffa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dampak Sosial'])[1]/following::a[1]</value>
      <webElementGuid>c5061cf6-86ac-4105-b56c-79bd3b285ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Kami'])[1]/following::a[2]</value>
      <webElementGuid>65d25382-a8f0-44b8-a532-b24fd9119ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/preceding::a[1]</value>
      <webElementGuid>f58b0ae0-dea5-4c73-9f5f-84831144ea74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::a[2]</value>
      <webElementGuid>09c8be82-8d64-467f-a511-c79d296df0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Karir']/parent::*</value>
      <webElementGuid>aee59ec9-389f-4fc2-ba6e-36614ba14a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/karir/')]</value>
      <webElementGuid>32e2d813-b375-4b21-9762-2c90d00b87f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>acefc118-4d00-4b61-825c-d2965059f131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/karir/' and (text() = 'Karir' or . = 'Karir')]</value>
      <webElementGuid>c2302ecd-e916-43e3-b291-0013050be969</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
