<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tentang Kami</name>
   <tag></tag>
   <elementGuidId>7f4d2947-8311-4221-81a6-671d5450d933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/header/div[2]/div/nav/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f12db402-fc75-4ec2-bba8-bded1874a2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white </value>
      <webElementGuid>6c338b2d-38b0-475c-a16c-e756006ea2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tentang-kami/</value>
      <webElementGuid>a2c2a001-8854-4897-b810-e18b57df3f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tentang Kami</value>
      <webElementGuid>353e2b44-e3c6-4cb5-94e8-82c91697945b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative w-screen antialiased __variable_241a51 __variable_43c742 font-sans&quot;]/div[@class=&quot;absolute top-0 z-10&quot;]/header[@class=&quot;sticky top-0 z-50 w-screen bg-transparent fadeInDown transition-all duration-1000&quot;]/div[@class=&quot;side-padding relative z-50 flex max-h-[120px] items-center justify-between py-10 text-white mobile:pb-4 tablet:pb-8&quot;]/div[1]/nav[@class=&quot;mx-4 flex&quot;]/ul[@class=&quot;flex flex-wrap items-center gap-[32px] gap-y-10 text-14 font-medium leading-6 laptop:text-16 desktop:gap-[72px]&quot;]/li[@class=&quot;group/menu relative border-white py-2 hover:border-b&quot;]/a[@class=&quot;text-white&quot;]</value>
      <webElementGuid>7bf74a8e-f7ae-4924-ba4e-7137706d8034</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/header/div[2]/div/nav/ul/li[3]/a</value>
      <webElementGuid>6a357b11-e25d-4188-9ba6-4686cc358754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tentang Kami')]</value>
      <webElementGuid>f76364e8-cbfa-483a-aa3f-00c19dbc89c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Decision Engine'])[1]/following::a[1]</value>
      <webElementGuid>e2cac07e-4252-4037-becd-07e87e8a1f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Embedded Investment'])[1]/following::a[2]</value>
      <webElementGuid>0a26e0e0-cca6-417c-ac03-dea0e6be04bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dampak Sosial'])[1]/preceding::a[1]</value>
      <webElementGuid>67d4d2b4-9bb3-4fcf-943a-8fb95606cc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karir'])[1]/preceding::a[2]</value>
      <webElementGuid>b631bae4-964e-40c3-b8dd-aafe60c17e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tentang Kami']/parent::*</value>
      <webElementGuid>8e17e27f-d7dd-497c-b648-7e7ec2501220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/tentang-kami/')]</value>
      <webElementGuid>fb797214-31c7-470c-bce6-de05903d55c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>190aeb3c-0422-4a52-93ea-0c8dc41d67c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/tentang-kami/' and (text() = 'Tentang Kami' or . = 'Tentang Kami')]</value>
      <webElementGuid>d1e76ce3-5303-4ca6-8789-f9f88e0f7b07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
