<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blog</name>
   <tag></tag>
   <elementGuidId>50f41fb9-fc1c-4e4c-a3ec-7acff664d226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/header/div[2]/div/nav/ul/li[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5730578c-4621-43d8-8639-d85930c7d60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-link-secondary </value>
      <webElementGuid>b9897d57-021c-4091-bc54-761ff2e49400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/blog/</value>
      <webElementGuid>0f8ff4f3-3011-42d4-84d0-d3db506ef4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>352a99b0-9a7e-4056-9967-13a699eeb498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;relative w-screen antialiased __variable_241a51 __variable_43c742 font-sans&quot;]/div[@class=&quot;absolute top-0 z-10&quot;]/header[@class=&quot;sticky top-0 z-50 w-screen bg-transparent fadeInDown transition-all duration-1000&quot;]/div[@class=&quot;side-padding relative z-50 flex max-h-[120px] items-center justify-between py-10 text-white mobile:pb-4 tablet:pb-8&quot;]/div[1]/nav[@class=&quot;mx-4 flex&quot;]/ul[@class=&quot;flex flex-wrap items-center gap-[32px] gap-y-10 text-14 font-medium leading-6 laptop:text-16 desktop:gap-[72px]&quot;]/li[@class=&quot;group/menu relative border-primary py-2 hover:border-b&quot;]/a[@class=&quot;text-link-secondary&quot;]</value>
      <webElementGuid>5565e6a2-12b6-4d92-a081-2263e95104c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/header/div[2]/div/nav/ul/li[6]/a</value>
      <webElementGuid>0809d6a9-977e-4e47-8bf2-4e90e0e65f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Blog')]</value>
      <webElementGuid>43959e75-f501-4ba1-a8d0-7733bbe864e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karir'])[1]/following::a[1]</value>
      <webElementGuid>d2492395-633c-46db-9be3-59c60f7e8127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dampak Sosial'])[1]/following::a[2]</value>
      <webElementGuid>5231999a-aec1-42a6-8766-60545f60d7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::a[1]</value>
      <webElementGuid>10f22ac7-64d3-42ca-82e4-d22b320a51ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individu'])[2]/preceding::a[1]</value>
      <webElementGuid>a7e6e03a-3cbf-4283-85b2-9307de87a17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blog']/parent::*</value>
      <webElementGuid>73fc9b14-33c7-43ac-8800-709e85d4d5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/blog/')]</value>
      <webElementGuid>6caaf5b7-76f5-4b7c-bc4e-63490397d06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>8a9c053c-17cd-4091-b0fc-1c48ee405496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/blog/' and (text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>d75d17f9-a464-46ac-8421-41e687bf65cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
